services:
  db:
    image: mysql:8.0.30
    container_name: docker-study-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3307:3306'
#    volumes:
#      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
  redis:
    image: redis:latest
    container_name: redis.admin-panel
    restart: always
    ports:
      - "6379:6379"
    #volumes:
    #  - /path/to/local/d–∞ta:/root/redis
    #  - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=${REDIS_DATABASES}
  mailhog:
      image: mailhog/mailhog
      container_name: 'docker-study-mailhog'
      ports:
        - "1025:1025"
        - "8025:8025"