services:
  db:
    image: mysql:8.0.30
    container_name: docker-study-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3307:3306'
#    volumes:
#      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
  mailhog:
      image: mailhog/mailhog
      container_name: 'docker-study-mailhog'
      ports:
        - "1025:1025"
        - "8025:8025"