services:
  jenkins:
    image: jenkins/jenkins:latest-jdk21
    container_name: jenkins.tests
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false # Skip initial setup wizard
    ports:
      - "${JENKINS_WEB_PORT}:8080"
      - "${JENKINS_INTERNAL_PORT}:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket for agent
      - ./jenkins_workspace:/home/jenkins/workspace